[info]
level = 2
title = "Subtract"
desc = "For each pair of two, return: subtract the second from the first, then subtract the first from the second."
inbox_example = "1, 3, 6, 7"
outbox_example = "-2, 2, -1, 1"

[game]
outbox = [-6, 6, 4, -4, 0, 0, 18, -18]
inbox = [3, 9, 5, 1, -2, -2, 9, -9]
available_instructions = ["inbox", "outbox", "add", "sub", "copyto", "copyfrom", "jump", "jumpifzero"]
available_tiles = 3

