[info]
level = 4
title = "From addition to multiplication"
desc = "First, get a 1 and do not return anything; Then, for each subsequent pair of two positive integers, return their product"
inbox_example = "1, 2, 3, 4, 5"
outbox_example = "6, 20"

[game]
outbox = [12, 12, 36, 5, 5]
inbox = [1, 3, 4, 4, 3, 6, 6, 1, 5, 5, 1]
available_instructions = ["inbox", "outbox", "add", "sub", "copyto", "copyfrom", "jump", "jumpifzero"]
available_tiles = 4 

